project_id_env: CROWDIN_SUBSTRATEDEVHUB_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "./"
preserve_hierarchy: true

files:
  -
    source: '/docs/**/*.md'
    translation: '/website/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'es-ES': 'es-ES'
        'ja': 'ja'
        'zh-CN': 'zh-CN'
        'zh-HK': 'zh-HK'
  -
    source: '/website/i18n/en.json'
    translation: '/website/i18n/%locale%.json'
    languages_mapping: *anchor

  # note: Uncomment the following if we have `website/versioned_docs`. Otherwise, returns
  #   error when running `crowdin upload sources` and fail the CI.
  # -
  #   source: '/website/versioned_docs/**/*.md'
  #   translation: '/website/translated_docs/%locale%/**/%original_file_name%'
  #   languages_mapping: *anchor
